# Generated by Django 4.0.4 on 2022-05-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish', 'title')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Continent'),
        ),
    ]
